# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for DeepL MCP Server
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Bundle app source
COPY . .

# Expose stdio run directly
CMD ["node", "src/index.mjs"]
